### ISSUE TITLE
Class WPMVC\Commands\SetCommand Not Found

### ISSUE THREAD

**Issue by piresashwin** [10quality/wpmvc#1]
Hello,

I installed the wpmvc framework. when i try to run

php ayuco setup - I am getting this error. Also cannot find the SetCommand Class in the vendors folder

Fatal error: Class 'WPMVC\Commands\SetCommand'

**Comment by amostajo** [comment]
That is because we have recently updated:
https://github.com/10quality/wpmvc/blob/v2.0/composer.json

The fix is easy, on your setup open you `composer.json` file and change this line:
```json
        "10quality/wpmvc-commands": "0.8.*"
```
to this:
```json
        "10quality/wpmvc-commands": "1.0.*"
```

Then on command-line application run:
```
composer update
```

**Comment by piresashwin** [comment]
It worked perfectly. Thank you so much for this amazing framework. It's making the work easier.

**Comment by 10quality-info** [comment]
;) I am still making tutorial notes wrapping things up though. Hopefully a
formal release is coming as soon

On Apr 22, 2017 8:52 AM, "Ashwin PIres" <notifications@github.com> wrote:

It worked perfectly. Thank you so much for this amazing framework. It's
making the work easier.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/10quality/wpmvc/issues/1#issuecomment-296378445>, or mute
the thread
